### ISSUE TITLE
Can you provide pre-trained model ?

### ISSUE THREAD

**Issue by oliviernguyenquoc** [MKLab-ITI/ndvr-dml#11]
Hi,

I would like to know if you can provide weights of your model or pretrained model ?

**Comment by gkordo** [comment]
Hi, sorry for the late response. You can find pretrained models [here](https://drive.google.com/drive/folders/1swgdUsYwOy9pdoJzKfthAq74CqBEQDmA?usp=sharing).

**Comment by SiyingLiang** [comment]
> Hi, sorry for the late response. You can find pretrained models [here](https://drive.google.com/drive/folders/1swgdUsYwOy9pdoJzKfthAq74CqBEQDmA?usp=sharing).

Hi, what are the parameters of the vgg_pretrained model ? In your paper, you just mentioned the models from AlexNet and GoogLeNet.

**Comment by gkordo** [comment]
We employed the feature extraction method described in this [paper](https://zenodo.org/record/240645#.XduWC9GxVhE). You can find the implementation in this [repo](https://github.com/MKLab-ITI/intermediate-cnn-features).

**Comment by SiyingLiang** [comment]
> We employed the feature extraction method described in this [paper](https://zenodo.org/record/240645#.XduWC9GxVhE). You can find the implementation in this [repo](https://github.com/MKLab-ITI/intermediate-cnn-features).

Sorry, I mean how are the parameters of DML model designed when you use the features from VGG.

**Comment by gkordo** [comment]
Oh, the VGG features are 4096 dimensions, and the outputs of the DML layers are [2000, 1000, 500] dimensions.

**Comment by SiyingLiang** [comment]
> Oh, the VGG features are 4096 dimensions, and the outputs of the DML layers are [2000, 1000, 500] dimensions.

Thank you very much !
