### ISSUE TITLE
When evaluate mAP of ccweb, it seems you didn't set any threshold of similarities?

### ISSUE THREAD

**Issue by xiaozhi2015** [MKLab-ITI/ndvr-dml#12]
Was the evaluate function in util.py created by yourself?
@gkordo

**Comment by gkordo** [comment]
Yes, I created the evaluation function that calculates the mAP on CC_WEB_VIDEO dataset.
The mAP calculation has been implemented based on the formula described in the original dataset's [paper](http://vireo.cs.cityu.edu.hk/papers/mm07wu1.pdf) (in Section 5.1), which does not consider any similarity threshold for the calculation.

**Comment by xiaozhi2015** [comment]
Much thx for your reply! @gkordo
