### ISSUE TITLE
generating training files according to our own data?

### ISSUE THREAD

**Issue by maida-shahid** [MKLab-ITI/ndvr-dml#13]
Respected Sir,
I know that you are using the **vcdb.pickle** file for the training of DML model. i also know that the pickle file is a dictionary containing **video pairs** and **index**.
i was wondering how can i generate the training files for my own dataset?

**Comment by gkordo** [comment]
To generate a similar file to **vcdb.pickle**, you have to know the percentage of overlap between the video pairs. More precisely, the **index** in the dictionary contains the list of video ids in the dataset, and the **video_pairs**  contains the list of video overlaps. The latter list consists of dictionaries (one for each video pair) that contain the index and the overlap of each video in the pair. For example:
```bash
[{'videos': [398, 370], 'overlap': [0.85, 1.0]},
 {'videos': [274, 280], 'overlap': [0.97, 0.39]},
 {'videos': [247, 243], 'overlap': [0.85, 0.56],
 ...
]
```
If you don't have information about the video overlaps you could either manually set it to 1.0 or consider using the function [triplet_generator_cc](https://github.com/MKLab-ITI/ndvr-dml/blob/53ca437a9b91a7a661ac63c9b1528ca456a0e291/triplet_generator.py#L117).
