### ISSUE TITLE
Where is the function for feature vectors fusion?

### ISSUE THREAD

**Issue by ryanaleksander** [MKLab-ITI/ndvr-dml#15]
I'm trying to calculate the distance between 2 individual videos. According to the paper, after extracting the feature vectors I've got a choice between early fusing and late fusion to turn the feature vectors into a single vector before feeding it to the embedding function, but I don't see where the process even happens.

**Comment by Thinktan** [comment]
@ryanaleksander Do you find this process?

**Comment by ryanaleksander** [comment]
@Thinktan No, I ended up implementing it myself

**Comment by gkordo** [comment]
I have added an option for late fusion functionality in the [evaluation.py](https://github.com/MKLab-ITI/ndvr-dml/blob/master/evaluation.py). Please, see [here](https://github.com/MKLab-ITI/ndvr-dml/blob/78a17932f16ec789c4aa0158452824080278cbbb/evaluation.py#L83).
