### ISSUE TITLE
about train/test subset divide

### ISSUE THREAD

**Issue by zouying-sjtu** [MKLab-ITI/ndvr-dml#18]
Hello, how about the way to split cc_web_video dataset to trainset and testset.
Thanks

**Comment by gkordo** [comment]
This repo does not provide such functionality. To run the code, the VCDB dataset is used for training and the CC_WEB_VIDEO for evaluation/test.

Thus, If you want to split the CC_WEB_VIDEO dataset in train and test set, you have to do it manually.
