### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Thinktan** [MKLab-ITI/ndvr-dml#19]
I download the feature and triplets form "https://drive.google.com/drive/folders/1swgdUsYwOy9pdoJzKfthAq74CqBEQDmA";
use vcdb_features.npy and vcdb_triplets.npy for train_dml;
the command is "python train_dml.py --train_set output_data/vcdb_features.npy --triplets output_data/vcdb_triplets.npy --model_path model/";
but it report system error:
can you help to resolve this problem ?
![image](https://user-images.githubusercontent.com/55999974/103477500-7e3cab00-4dfa-11eb-861f-59da1622659c.png)

**Comment by Thinktan** [comment]
@gkordo

**Comment by gkordo** [comment]
Thank you for the bug report. It was an issue with the dtype of the triplets' np.array, causing this error. I have fixed it in the latest commit. Please, pull the latest version and let me know if it works.

**Comment by Thinktan** [comment]
@gkordo already resolved，thanks
