### ISSUE TITLE
Request FIVR-200K dataset 

### ISSUE THREAD

**Issue by willard-yuan** [MKLab-ITI/ndvr-dml#2]
@gkordo Hi Giorgos,

I have read your paper "FIVR: Fine-grained Incident Video Retrieval" and I'm interested in the dataset of FIVR-200K which you will release [ndd.iti.gr/fivr.html](http://ndd.iti.gr/fivr.html). Would you like to tell me when to release the FIVR-200K so I can use the dataset to do some experiments.

Thanks.

**Comment by gkordo** [comment]
@willard-yuan Hi Yuan,

Thanks for your interest in our work. Please use this board solely for issues related to the repository. Also, please contact us via email to ask for the dataset.
