### ISSUE TITLE
How to generate the file ./datasets/cc_web_video.pickle

### ISSUE THREAD

**Issue by Aionrichman** [MKLab-ITI/ndvr-dml#20]
Is there any description or generate method for pickle files?

**Comment by xsyzka** [comment]
I want to know, too

**Comment by gkordo** [comment]
Hi and sorry for that late response :)
Both `.pickle` files were generated based on the datasets' annotations provided by the original authors. In particular, `cc_web_video.pickle` was generated based on the annotation provided by the [VIREO group](http://vireo.cs.cityu.edu.hk/) in the [CC_WEB_VIDEO website](http://vireo.cs.cityu.edu.hk/webvideo/).
To this end, unfortunately, there is no standard process to generate a similar file cause I did that for each dataset independently.
