### ISSUE TITLE
有大佬知道这个代码可以复现论文中的结果吗

### ISSUE THREAD

**Issue by xsyzka** [MKLab-ITI/ndvr-dml#23]

**Comment by gkordo** [comment]
Based on Google Translate, this issue reads:  "Does anyone know if this code can reproduce the results in the paper?"
Well, yes it does. :) 
You can use the pretrained models from [here](https://drive.google.com/drive/folders/1swgdUsYwOy9pdoJzKfthAq74CqBEQDmA).

**Comment by xsyzka** [comment]
> 根据谷歌翻译，这个问题的内容是：“有人知道这段代码是否可以重现论文中的结果吗？” 嗯，是的。:) 您可以使用[此处](https://drive.google.com/drive/folders/1swgdUsYwOy9pdoJzKfthAq74CqBEQDmA)的预训练模型。

**Comment by xsyzka** [comment]
Thank you very much.
