### ISSUE TITLE
Availability of Testing code?

### ISSUE THREAD

**Issue by maida-shahid** [MKLab-ITI/ndvr-dml#8]
Thank you for sharing such great information on training and evaluation of your model.
i was wondering if we need to visualize what videos are near duplicates of our input test video, how this can be done using your code?

**Comment by gkordo** [comment]
Having a trained model, you can initialize a [DNN](https://github.com/MKLab-ITI/ndvr-dml/blob/bfaa29bc7ee5c3a47de5f5f0d053410225212512/model.py#L23) object by providing the required argument, and then use the [embedding function](https://github.com/MKLab-ITI/ndvr-dml/blob/bfaa29bc7ee5c3a47de5f5f0d053410225212512/model.py#L202) to extract the final video representations. This is exactly what I am doing to evaluate the model performance on CC_WEB_VIDEO dataset, see [here](https://github.com/MKLab-ITI/ndvr-dml/blob/bfaa29bc7ee5c3a47de5f5f0d053410225212512/evaluation.py#L62). Also, see the following example:
```bash
features = np.load(path_to_features)
model = DNN(features.shape[1],
             path_to_model,
             load_model=True,
             trainable=False)
video_embeddings = model.embeddings(features)
```

Once you have extracted the video embeddings, you may use any dimensionality reduction algorithm (e.g. PCA, tSNE) to transform vectors to 2 or 3 dimension. I would recommend to use the same color for all near duplicates of a particular query, in case you already have such information.

**Comment by maida-shahid** [comment]
Thank you so much for the quick response.

Maida Shahid
Ms Intern
Al-Khawarizmi Institute of Computer Science,
UET Lahore

**Comment by maida-shahid** [comment]
Thanks!
